app:
  databases:
    - name: DB1
      type: POSTGRESQL
      url: jdbc:postgresql://localhost:5432/homidb
      username: homi2022
      password: homi2022
      connectionProperties:
        ssl: false
      envProperties:
          enableDatetimeFormatting: true
          timeFormat: 'HH:mm:ss'
          dateFormat: 'dd-MM-yyyy'
          dateTimeFormat: 'dd-MM-yyyy HH:mm:ss'
          defaultFetchLimit : 100



