app:
  version: @project.version@
  name: @project.name@

  databases:
    - id: ${DB_ID:db}
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      schemas: ${INCLUDED_SCHEMAS}

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework

  compression:
    enabled: ${GZIP_ENABLED:false}
    mime-types: application/json
    min-response-size: {GZIP_MIN_RESPONSE_SIZE:1024}
    # excluded-user-agents: MSIE 6.0,UCBrowser


spring:

  threads:
    virtual:
      enabled: true

  banner:
    location: classpath:banner.txt

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB


db2rest:

  auth:
    enabled: ${ENABLE_AUTH:false}
    provider: ${AUTH_PROVIDER:basic}
    data:
      source: ${AUTH_DATA_SOURCE}


  dateTime:
    enableDataTimeFormatting: ${ENABLE_DATETIME_FORMATTING:false}
    timeFormat: ${TIME_FORMAT:HH:mm:ss}
    dateFormat: ${DATE_FORMAT:yyyy-MM-dd}
    dateTimeFormat: ${DATE_TIME_FORMAT:yyyy-MM-dd HH:mm:ss}

  defaultFetchLimit: ${DEFAULT_FETCH_LIMIT:100}

  allowSafeDelete : ${ALLOW_SAFE_DELETE:true}

  multiTenancy:
    enabled: ${MULTI_TENANCY_ENABLED:false}
    mode: ${MULTI_TENANCY_MODE:'NONE'}

logging:
  level:
    com.homihq.db2rest.rest: INFO
    com.homihq.db2rest.jdbc.core.service: INFO

    org.springframework.web : INFO
    org.springframework.beans : INFO
    org.springframework.jdbc: INFO



management:
  endpoints:
    web:
      exposure:
        include: "health,info,httpexchanges,prometheus,metrics"
  datadog:
    metrics:
      export:
        enabled: ${DATADOG_EXPORT_ENABLED:false}
        api-key: ${DATADOG_API_KEY}
        application-key: ${DATADOG_APPLICATION_KEY}
        uri: ${DATADOG_EXPORT_URI}
        step: ${DATADOG_EXPORT_INTERVAL:30s}

  prometheus:
    metrics:
      export:
        enabled: ${PROMETHEUS_EXPORT_ENABLED:false}


