app:
  version: @project.version@
  name: @project.name@

  databases:
    - id: ${DB_ID:db}
      url: ${DB_URL:}
      username: ${DB_USER:}
      password: ${DB_PASSWORD:}

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework

  compression:
    enabled: ${GZIP_ENABLED:false}
    mime-types: application/json
    min-response-size: 1024
    # excluded-user-agents: MSIE 6.0,UCBrowser


spring:

  threads:
    virtual:
      enabled: true

  banner:
    location: classpath:banner.txt

  thymeleaf:
    check-template-location: false
    cache: true

db2rest:

  dateTime:
    enableDataTimeFormatting: ${ENABLE_DATETIME_FORMATTING:false}
    timeFormat: ${TIME_FORMAT:HH:mm:ss}
    dateFormat: ${DATE_FORMAT:yyyy-MM-dd}
    dateTimeFormat: ${DATE_TIME_FORMAT:yyyy-MM-dd HH:mm:ss}

    defaultFetchLimit: ${DEFAULT_FETCH_LIMIT:100}

  auth:
    enabled: ${AUTH_ENABLED:false}
    jwt:
      algorithm: HMAC256
      secret: abc
      issuers:
        - a
        - b
    data:
      # file: ${user.home}/git/db2rest/auth/auth-sample.yml
      api-endpoint: 'https://api.npoint.io/25e777e70e3a62289dc7'
      api-key: 123

  unKeyDev:
    enabled: ${UNKEY_DEV_ENABLED:false}
    url: ${UNKEY_DEV_URL}
    rootKey: ${UNKEY_DEV_ROOT_KEY}

  jwt:
    secret: ${JWT_SECRET_KEY}

  allowSafeDelete : ${ALLOW_SAFE_DELETE:true}

  multiTenancy:
    enabled: ${MULTI_TENANCY_ENABLED:false}
    mode: ${MULTI_TENANCY_MODE:'NONE'}

logging:
  level:
    com.homihq.db2rest:
      rest: INFO
      jdbc.service: INFO
    org.springframework.web : INFO
    org.springframework.beans : INFO
    org.springframework.jdbc: INFO

