app:
  version: 1.0.0-SNAPSHOT
  name: db2rest


server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework


spring:

  threads:
    virtual:
      enabled: true

  banner:
    location: classpath:banner.txt

  thymeleaf:
    check-template-location: false
    cache: true

db2rest:

  dateTime:
    enableDataTimeFormatting: ${ENABLE_DATETIME_FORMATTING:false}
    timeFormat: ${TIME_FORMAT:HH:mm:ss}
    dateFormat: ${DATE_FORMAT:yyyy-MM-dd}
    dateTimeFormat: ${DATE_TIME_FORMAT:yyyy-MM-dd HH:mm:ss}

    defaultFetchLimit: ${DEFAULT_FETCH_LIMIT:100}

  auth:
    type: ${AUTH_TYPE:none}

  unKeyDev:
    enabled: ${UNKEY_DEV_ENABLED:false}
    url: ${UNKEY_DEV_URL}
    rootKey: ${UNKEY_DEV_ROOT_KEY}

  jwt:
    secret: ${JWT_SECRET_KEY}

  allowSafeDelete : ${ALLOW_SAFE_DELETE:true}

  multiTenancy:
    enabled: ${MULTI_TENANCY_ENABLED:false}
    mode: ${MULTI_TENANCY_MODE:'NONE'}

logging:
  level:
    com.homihq.db2rest:
      rest: INFO
      jdbc.service: INFO
    org.springframework.web : DEBUG
    org.springframework.beans : INFO
    org.springframework.jdbc: INFO
