app:
  version: @project.version@
  name: @project.name@

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework


spring:

  threads:
    virtual:
      enabled: true

  datasource:

    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 10
      pool-name: db2rest-platform-hikari-pool
      data-source-properties:
        reWriteBatchedInserts: true

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB_NAME}

  banner:
    location: classpath:banner.txt

db2rest:
  dateTime:
    enableDataTimeFormatting: ${ENABLE_DATETIME_FORMATTING:false}
    timeFormat: ${TIME_FORMAT:HH:mm:ss}
    dateFormat: ${DATE_FORMAT:yyyy-MM-dd}
    dateTimeFormat: ${DATE_TIME_FORMAT:yyyy-MM-dd HH:mm:ss}

  defaultFetchLimit: ${DEFAULT_FETCH_LIMIT:100}
  datasource:
    type: ${DATASOURCE_TYPE:jdbc}
  includeSchemas: ${INCLUDE_SCHEMAS:#{null}}

  auth:
    type: ${AUTH_TYPE:none}

  unKeyDev:
    enabled: ${UNKEY_DEV_ENABLED:false}
    url: ${UNKEY_DEV_URL}
    rootKey: ${UNKEY_DEV_ROOT_KEY}

  jwt:
    secret: ${JWT_SECRET_KEY}

  allowSafeDelete : ${ALLOW_SAFE_DELETE:true}

  multiTenancy:
    enabled: ${MULTI_TENANCY_ENABLED:false}
    mode: ${MULTI_TENANCY_MODE:'NONE'}


d1:
  accountId: ${D1_ACCOUNT_ID}
  dbId: ${D1_DB_ID}
  apiKey: ${D1_API_KEY}


logging:
  level:
    com.homihq.db2rest:
      rest: INFO
      jdbc.service: INFO
    org.springframework.web : DEBUG
    org.springframework.beans : INFO
    org.springframework.jdbc: INFO
