app:
  version: @project.version@
  name: @project.name@

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
  servlet:
    session:
      timeout: 90m

spring:

  threads:
    virtual:
      enabled: true

  datasource:

    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 10
      pool-name: db2rest-platform-hikari-pool
      data-source-properties:
        reWriteBatchedInserts: true

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB_NAME}
      #host: ${MONGODB_HOST}
     # port: ${MONGODB_PORT}
      #database: ${MONGODB_DB_NAME}
      #username: ${MONGODB_USER}
      #password: ${MONGODB_PASSWORD}

  banner:
    location: classpath:banner.txt

db2rest:
  defaultFetchLimit: ${DEFAULT_FETCH_LIMIT:100}
  datasource:
    type: ${DATASOURCE_TYPE:jdbc}

    includeTables: ${INCLUDE_TABLES:}
    includeCatalogs: ${INCLUDE_CATALOGS:#{null}}
  includeSchemas: ${INCLUDE_SCHEMAS:#{null}}

  auth:
    type: ${AUTH_TYPE:none}

  unKeyDev:
    enabled: ${UNKEY_DEV_ENABLED:false}
    url: ${UNKEY_DEV_URL}
    rootKey: ${UNKEY_DEV_ROOT_KEY}

  jwt:
    secret: ${JWT_SECRET_KEY}

  allowSafeDelete : ${ALLOW_SAFE_DELETE:true}

  multiTenancy:
    enabled: ${MULTI_TENANCY_ENABLED:false}
    mode: ${MULTI_TENANCY_MODE:'NONE'}


d1:
  accountId: ${D1_ACCOUNT_ID}
  dbId: ${D1_DB_ID}
  apiKey: ${D1_API_KEY}


logging:
  level:
    com.homihq.db2rest:
      rest: DEBUG
      jdbc.service: DEBUG
    org.springframework.web : INFO
    org.springframework.beans : INFO
    schemacrawler.schemacrawler: ERROR
    schemacrawler.crawl: ERROR
    us.fatehi.utility.scheduler: ERROR
    org.springframework.jdbc: DEBUG
