server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    session:
      timeout: 90m

spring:
  threads:
    virtual:
      enabled: true


  datasource:
    hikari:
      maximum-pool-size: 10
      pool-name: db2rest-platform-hikari-pool
      data-source-properties:
        reWriteBatchedInserts: true

db2rest:
  allowSafeDelete : false
  schemas: ${DB_SCHEMAS}


logging:
  level:
    org.springframework.web : INFO
