server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    session:
      timeout: 90m

spring:

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 10
      pool-name: db2rest-platform-hikari-pool
      data-source-properties:
        reWriteBatchedInserts: true

db2rest:
  datasource:
    type: d1
  unKeyDev:
    enabled: ${UNKEY_DEV_ENABLED:false}
    url: ${UNKEY_DEV_URL}
    rootKey: ${UNKEY_DEV_ROOT_KEY}

  allowSafeDelete : ${ALLOW_SAFE_DELETE:true}

  multiTenancy:
    enabled: ${MULTI_TENANCY_ENABLED:false}
    mode: ${MULTI_TENANCY_MODE:'NONE'}


d1:
  accountId: ${D1_ACCOUNT_ID}
  dbId: ${D1_DB_ID}
  apiKey: ${D1_API_KEY}


logging:
  level:
    com.homihq.db2rest:
      rest: DEBUG
    org.springframework.web : INFO
    schemacrawler:
      schemacrawler: ERROR
      crawl: ERROR
    us:
      fatehi:
        utility:
          scheduler: ERROR
    org:
      springframework:
        web: INFO
        test:
          context:
            jdbc: DEBUG

        jdbc:
          datasource:
            init: DEBUG
          core.*: DEBUG
