
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}


db2rest:
  allowSafeDelete : ${ALLOW_UNSAFE_DELETE:true}
  schemas: ${DB_SCHEMAS}
  multiTenancy:
    enabled: ${MULTI_TENANCY_ENABLED}
    mode: ${MULTI_TENANCY_MODE}
