server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    session:
      timeout: 90m

spring:

  threads:
    virtual:
      enabled: true


  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 10
      pool-name: db2rest-platform-hikari-pool
      data-source-properties:
        reWriteBatchedInserts: true

db2rest:
  allowSafeDelete : true
  schemas: ${DB_SCHEMAS}
  multiTenancy:
    enabled: ${MULTI_TENANCY_ENABLED:false}
    mode: ${MULTI_TENANCY_MODE:'NONE'}


logging:
  level:
    com.homihq.db2rest:
      rest: DEBUG
    org.springframework.web : INFO
    schemacrawler:
      schemacrawler: ERROR
      crawl: ERROR
    us:
      fatehi:
        utility:
          scheduler: ERROR
    org:
      springframework:
        web: INFO
        test:
          context:
            jdbc: DEBUG

        jdbc:
          datasource:
            init: DEBUG
