services:
  db2rest-service:
    image: kdhrubo/db2rest:latest
    ports:
      - 80:8080
    environment:
      DB_URL: "jdbc:mariadb://employee-mariadb:3306/empdb"
      DB_USER: "db2rest"
      DB_PASSWORD: "db2rest"
      INCLUDED_SCHEMAS: public,emp
    depends_on:
      - employee-mariadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  employee-mariadb:
    image: "mariadb:10.6"
    container_name: "employee-mariadb"
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=db2rest
      - MYSQL_PASSWORD=db2rest
      - MYSQL_DATABASE=empdb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5

volumes:
  mariadb-data:
