name: Build & Verify

on:
  workflow_dispatch:
      inputs:
        version:
          description: 'Version to publish'
          required: true
          default: '1.3.0-SNAPSHOT'
        ref:
          description: 'Type the Branch, Tag or SHA to use for publishing Snapshot'
          required: false
          default: 'master'
  pull_request:
    paths-ignore:
      -
    branches:
      - master
  push:
    branches:
      - 'feature/**'
jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -B verify --file pom.xml
      
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      #- name: Update dependency graph
      #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
