name: Build & Verify

on:
  pull_request:
    paths-ignore:
      -
    branches:
      - master
  push:
    branches:
      - 'feature/**'

env: 
  VERSION: '1.3.1-SNAPSHOT'

jobs:
  build:
    name: Maven Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: 'maven'

      - name: Build & Test
        run: ./mvnw -Drevision=$VERSION --no-transfer-progress -B verify --file pom.xml
      
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      #- name: Update dependency graph
      #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
