# This workflow will download the Maven Central package and
# build Docker image and publish to DockerHub  

name: Download from Central & Publish to DockerHub

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Download DB2REST packages from Maven Central
        run: |
          echo "---------^^^^^^^^^^^^^^^^^^-------------"
          echo "CHANGE THIS STEP SO THAT IT SUCCESSFULLY"
          echo "  PULLS OUR DB2REST PACKAGE FROM MAVEN CENTRAL"
          echo "  NOW THAT WE'RE ON THAT"
          echo "  THEN UNCOMMENT THE REMAINING STEPS IN THIS WORKFLOW"

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push Docker images
      #   uses: docker/build-push-action@v3.2.0
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     push: true
      #     tags: kdhrubo/db2rest:v${{github.run_number}}, kdhrubo/db2rest:latest
