# This workflow will download the Maven Central package and
# build Docker image and publish to DockerHub  

name: Publish to DockerHub

on:
  workflow_dispatch:
    inputs:
      DB2REST_VERSION:
        description: 'DB2REST version that is already published in Maven Central'
        required: true
        default: '1.3.0'
    
  # release:
  #   types: [created]

jobs:
  build_docker_image:

    runs-on: ubuntu-latest
    env:
      DB2REST_VERSION: ${{ github.event.inputs.DB2REST_VERSION }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # In this following step, we use our Dockerfile
      # to build the image (which has a `ADD` line to automatically
      # download the versioned JAR file from Central Portal and
      # adds it into a layer of the image)
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
      # We use default Git context to build the Docker image,
      # instead of PATH context `context: .`
          push: true
          tags: kdhrubo/db2rest:v${{ github.run_number }}, kdhrubo/db2rest:latest
          build-args: DB2REST_VERSION=${{ env.DB2REST_VERSION }}
