# This workflow will build a package using Maven and then publish it to Central Portal (Sonatype)
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Default Publish

on:
  release:
    types: [created]

jobs:
  job1_publish_to_mavencentral:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      name: Checkout code for Tag
      with:
        ref: ${{ github.event.release.tag_name }}
    - name: Echo Tag
      run: "echo 'CHECKED OUT TAG: ${{ github.event.release.tag_name }}'"
    - name: Set up JDK 21 and maven settings.xml
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'liberica'
        cache: 'maven'
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        server-id: central

    - name: Build & Publish package DB2Rest to Central
      run: mvn -Drevision=${{ github.event.release.tag_name }} --no-transfer-progress -B deploy -P release -DskipTests
      # below we use env for passing GPG stuff since the signing type is bouncy castle (bc)
      # set in parent pom's maven-gpg-plugin configuration and doesn't need gpg agent.
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}

    - run: |
        mkdir staging
        ls -ll
        ls -ll target
        cp target/*.jar staging
        ls -ll staging

    - name: Archive JAR artifact
      uses: actions/upload-artifact@v4
      with:
        path: staging

    # - name: Build & Publish package Oracle9i to Central
    #   run: mvn -Drevision=${{ github.event.release.tag_name }} --no-transfer-progress -B deploy -P release --file api-rest/pom-oracle9i.xml -DskipTests
    #   env:
    #     MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
    #     MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
    #     MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    #     MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}

    # - name: Login to DockerHub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v6
    #   with:
    #     push: true
    #     tags: kdhrubo/db2rest:v${{ github.event.release.tag_name }}, kdhrubo/db2rest:latest
    #     build-args: DB2REST_VERSION=${{ github.event.release.tag_name }} JAR_FILE=staging/db2rest-${{ github.event.release.tag_name }}.jar
