# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Default Publish

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      name: Checkout code for Tag
      with:
        ref: ${{ github.ref }}
    - name: Echo Tag
      run: "echo 'CHECKED OUT TAG: ${{ github.ref }}'"
    - name: Set up JDK 21 and maven settings.xml
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'liberica'
        cache: 'maven'
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        server-id: central

    - name: Publish package DB2Rest
      run: mvn -Drevision=${{ github.ref }} --no-transfer-progress -B deploy -P release -DskipTests
      # below we use env for passing GPG stuff since the signing type is bouncy castle (bc)
      # set in parent pom's maven-gpg-plugin configuration and doesn't need gpg agent.
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}

    - name: Publish package Oracle9i
      run: mvn -Drevision=${{ github.ref }} --no-transfer-progress -B deploy -P release --file api-rest/pom-oracle9i.xml -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
