name: Pull Request E2E Test

on:
  workflow_dispatch:
    
  pull_request:
    paths-ignore:
      -
    branches:
      - master

permissions: read-all

jobs:
  e2e_test:
    name: e2e_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 21
          cache: 'maven'

      # - name: Start test containers for DB's
      #   run: docker-compose up -d

      - name: Compile & Test with DB Containers
        run: mvn -B test --file pom.xml

      # - name: Stop test containers for DB's
      #   run: docker-compose down
